// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHtmM9lwRHc3D77rBROFMhViw_Te0rM-4',
    appId: '1:196758291330:web:d48fc48e57697cb203459b',
    messagingSenderId: '196758291330',
    projectId: 'hospital-64e11',
    authDomain: 'hospital-64e11.firebaseapp.com',
    storageBucket: 'hospital-64e11.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAdd1SiYkz56KwBHVsH4BGKQhAWBcq2ak',
    appId: '1:196758291330:android:9a758a3bdfeaf69703459b',
    messagingSenderId: '196758291330',
    projectId: 'hospital-64e11',
    storageBucket: 'hospital-64e11.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJIg-toHPhoQ7J2vi8KPvYu_n9iUSuqoY',
    appId: '1:196758291330:ios:b53f23c2f3925e1f03459b',
    messagingSenderId: '196758291330',
    projectId: 'hospital-64e11',
    storageBucket: 'hospital-64e11.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJIg-toHPhoQ7J2vi8KPvYu_n9iUSuqoY',
    appId: '1:196758291330:ios:b53f23c2f3925e1f03459b',
    messagingSenderId: '196758291330',
    projectId: 'hospital-64e11',
    storageBucket: 'hospital-64e11.firebasestorage.app',
    iosBundleId: 'com.example.doctor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHtmM9lwRHc3D77rBROFMhViw_Te0rM-4',
    appId: '1:196758291330:web:7f3a060bff80ced303459b',
    messagingSenderId: '196758291330',
    projectId: 'hospital-64e11',
    authDomain: 'hospital-64e11.firebaseapp.com',
    storageBucket: 'hospital-64e11.firebasestorage.app',
  );
}
